### ISSUE TITLE
Bug when using more than one query parameter

### ISSUE THREAD

**Issue by vpaulino** [codesenberg/bombardier#104]
This is an example of what a **bug report** can look like. Please, feel free to also provide any other information relevant to the issue.

### What version of bombardier are you using?
Hash of the commit, like 

[00d7965d6cae34c62042abb0f6c45c45b870dcf3](https://github.com/codesenberg/bombardier/commit/00d7965d6cae34c62042abb0f6c45c45b870dcf3)

in case you've built _bombardier_ yourself or version obtained by
```
Executing --version I have "bombardier version unspecified windows/amd64
```

in case you are using binaries.

### What operating system and processor architecture are you using (if relevant)?
  `windows/amd64`, 

### What did you do?

I have an aspnet core 7 application running attached with visual studio available to test at the usual https ports that visual studio generates. The endpoint Im executing contains two query parameters and when I try to execute bombardier to GET resources from that endpoint he executes the request but only using the first query parameter, the following ones are wrongly interpreted as an atemptive to use a comand.  Here is a print screen: 

![image](https://github.com/codesenberg/bombardier/assets/859157/9d52798f-9c63-42a6-94ef-caea83f48619)

Describe steps that can be used to reproduce the error.

1- > bombardier https://localhost:7033/api/v1/products?take=50&lastProductID=0

### What you expected to happen?
to execute the http request using both parameters correctly 

### What actually happened?
The request was made but using only one parameter. the following ones by the error message are wrong interpreted as bombardier commands.

**Comment by codesenberg** [comment]
If you look closely at the bottom of your screenshot, you'll see:
![image](https://github.com/codesenberg/bombardier/assets/6357982/0200cc72-0ee1-4bda-9dc6-be4bb1fcae48)

Judging by the path and error messages, this is [`cmd.exe`](https://en.wikipedia.org/wiki/Cmd.exe) and what happens is `cmd.exe` interprets you command `bombardier https://localhost:7033/api/v1/products?take=50&lastProductID=0` something like:
1. Execute `bombardier` command and pass it `https://localhost:7033/api/v1/products?take=50` argument;
2. `&` - and then;
3. Execute `lastProductID` command (guess `=0` becomes an argument, but irrelevant here), which `cmd.exe` doesn't recognize.

What you should be doing is surrounding the URL with double quotes, like so:
```console
bombardier "https://localhost:7033/api/v1/products?take=50&lastProductID=0"
```
