### ISSUE TITLE
package _/root: unrecognized import path "_/root" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by junoteam** [codesenberg/bombardier#11]
when do:
```
go get -u github.com/codesenberg/bombardier .
```
get this error:
```
package _/root: unrecognized import path "_/root" (import path does not begin with hostname)
```

Can you help?

**Comment by codesenberg** [comment]
@junoteam, sure. The dot at the end of your command is the cause of this error. Remove it.
You probably copied it from **README.md**, so, I removed it from there too.

**Comment by junoteam** [comment]
Thank you. 
It worked perfect!
