### ISSUE TITLE
URL without https/http prefix

### ISSUE THREAD

**Issue by junoteam** [codesenberg/bombardier#12]
Hey, 

if I put URL without prefix, I get error:   
`
bombardier -c 200 -d 30s -l ya.ru
parse ya.ru: invalid URI for request
`
or  
`
bombardier -c 200 -d 30s -l www.ya.ru
parse www.ya.ru: invalid URI for request
`
Don't you think it will good idea to add it automatically?

**Comment by codesenberg** [comment]
@junoteam, yeah, I thought about that too. It seems reasonable to default to `http` scheme if none present. Will work on it.

**Comment by codesenberg** [comment]
@junoteam, done. Feel free to reopen if you encounter any related bugs.

**Comment by junoteam** [comment]
Thanks!
