### ISSUE TITLE
Installation panic

### ISSUE THREAD

**Issue by peterbe** [codesenberg/bombardier#13]
See https://gist.github.com/peterbe/7ce8e70a36130fb3e2de18fd33eb7873

**Comment by codesenberg** [comment]
This isn't the issue with `bombardier`. It looks like you have ran into golang/go#17912.

Things to try:
* use newer version of `go`;
* use [precompiled binaries](https://github.com/codesenberg/bombardier/releases/tag/v1.0).

Also, [this table](https://github.com/golang/go/wiki/Darwin) might clarify some things.

**Comment by peterbe** [comment]
You're totally right. It works now. 
I haven't done any Go development for a year now.
