### ISSUE TITLE
feature: body from file

### ISSUE THREAD

**Issue by codesenberg** [codesenberg/bombardier#19]
Pasting and escaping large request bodies into a terminal is super inconvenient, therefore, it'd be nice to have an ability to read request body from file. It's up to user whether file will be read to the memory completely or served from disk every time. I plan to add two flags:
* `--body-from-disk` to read the body from disk each time;
* `--body-from-mem` to read the file into memory.

Suggestions on this are welcomed.

**Comment by aminearbi** [comment]
is this still valid ?

**Comment by codesenberg** [comment]
@aminearbi, what do you mean? If you meant "Is this feature implemented or not? Will it be?", then no, it's not implemented yet, but it will be at some later point. There is no ETA though.
