### ISSUE TITLE
feature: use dpdk on linux to improve performance and reduce CPU usage

### ISSUE THREAD

**Issue by qiuyi21** [codesenberg/bombardier#20]
In my testing, bombardier and ksoftirqd uses all CPU and became the bottleneck. Is possible that working with DPDK?

**Comment by codesenberg** [comment]
Hmm... _bombardier_ probably could use _dpdk_, but I have no plans for this. I feel like adding _dpdk_ would require quite a lot of effort and will compilate the build process.

**Comment by codesenberg** [comment]
Since this feature is not planned to be implemented any time soon (or at all) I'll close the issue for the time being.
