### ISSUE TITLE
multipart/form-data ?

### ISSUE THREAD

**Issue by her** [codesenberg/bombardier#21]
Hi,

I'm trying to load a test a binary upload endpoint using multipart/form-data and was wondering if it's possible to make bombardier handle this type of request? 

thanks!

**Comment by codesenberg** [comment]
Yes, if I understood what you are trying to achieve correctly, then I believe you can do this by crafting the response manually and setting appropriate header. Like this:
```bash
bombardier -H "Content-Type: multipart/form-data; boundary=Asrf456BGe4h" -m POST -f body.txt http://somehost:someport/path/to/your/endpoint/here
```
body.txt:
```
--Asrf456BGe4h
Content-Disposition: form-data; name="DestAddress"

someone@example.com
--Asrf456BGe4h
Content-Disposition: form-data; name="MessageTitle"

Hello!
--Asrf456BGe4h
Content-Disposition: form-data; name="MessageText"

Hello, this is a text.
--Asrf456BGe4h
Content-Disposition: form-data; name="AttachedFile1"; filename="photo-1.jpg"
Content-Type: image/jpeg

345345345
--Asrf456BGe4h
Content-Disposition: form-data; name="AttachedFile2"; filename="photo-2.jpg"
Content-Type: image/jpeg

123123
--Asrf456BGe4h--

```

**Comment by her** [comment]
Thanks for the reply @codesenberg !!

I'm working on testing an endpoint that expects to receive a binary file (jpeg/png) following your examples (thank you so much for that!) I'm trying this now

bombardier:
`bombardier --header="Content-Type: multipart/form-data; boundary=3d1f25d78dbb7995" --method=POST --requests=1 --body-file=body.txt "http://127.0.0.1:3333/v1/upload_bin?param=int&params=more&again=stuff&finally=thing"`


`body.txt`:
```
--3d1f25d78dbb7995
Content-Disposition: form-data; name="file1"; filename="file1.jpg"
Content-Type: image/jpeg
--3d1f25d78dbb7995
```

my server is returning an `EOFError` and is receiving an empty body 😔

when I use cURL I do

`curl -F "data=@file1.jpg" "localhost:3333/v1/upload_bin?param=int&params=more&again=stuff&finally=thing"`

_which works_ but...

I'm not clear on how to pass the concept of `data=@file1.jpg` to bombardier, or if maybe I should also be passing query params in my `body.txt` as a `application/x-www-form-urlencoded` ? 

This is a Sinatra app that is running on Rack/Puma so the server error I get is like this: 
`2017-11-21 11:09:16 -0800: Rack app error handling request { POST /v1/upload_bin }
#<EOFError: EOFError>` 

with the method error as `2017-11-21 11:04:30 - NoMethodError - undefined method `[]' for nil:NilClass:` 

Just wanted to include those in case anyone else comes across this issue in the future, maybe it helps them. I'd also be happy to make a small PR if you'd like for documentation assuming I can get this working, so that maybe others can have an example of how to handle a binary upload of image data. I know it's something I've stumbled on with other frameworks. I really like bombardier though and would like to help give back if possible! 

Thanks again for your reply! Cheers!!

**Comment by codesenberg** [comment]
> my server is returning an EOFError and is receiving an empty body 😔

That makes sense, because in your _body.txt_ you forgot to specify the body of the file. I think that's the reason of the error. So you do it like:
```
--3d1f25d78dbb7995
Content-Disposition: form-data; name="file1"; filename="file1.jpg"
Content-Type: image/jpeg
{- you need to add a new line here -}
{- and the bytes of your picture go here -}
--3d1f25d78dbb7995--
```
cURL's ```data=@file1.jpg``` uses _multipart/form-data_.
Like, if you have:
```bash
curl -F "data=@file1.jpg" "localhost:3333/v1/upload_bin?param=int&params=more&again=stuff&finally=thing"
```
It loosely translates into:
```bash
bombardier -m POST -H "Content-Type: multipart/form-data; boundary=------------------------c3f12cad39483b9a" -f body.txt "localhost:3333/v1/upload_bin?param=int&params=more&again=stuff&finally=thing"
```
And in _body.txt_ you have:
```
--------------------------c3f12cad39483b9a
Content-Disposition: form-data; name="data"; filename="file1.jpg"
Content-Type: image/jpeg

{- content of file1.jpg -}
--------------------------c3f12cad39483b9a--
```
Actually, I just realized how nontrivial and inconvenient to craft these requests, but not sure how common are they. Maybe I should write some little tool to make crafting this type of bodies more convenient?

**Comment by her** [comment]
Thanks again for the reply @codesenberg 

>in your body.txt you forgot to specify the body of the file.

Aha!

I noticed yesterday when running curl through netcat that curl sends the byte stream between the boundaries to the server which having seen that and reading your comment it not seems so obvious😅 

So I've tried a couple different ways of adding the content of a jpg to body.txt in binary and base64.

binary snippet
```
00000000: ffd8 ffe0 0010 4a46 4946 0001 0100 0048  ......JFIF.....H
00000010: 0048 0000 ffe1 004c 4578 6966 0000 4d4d  .H.....LExif..MM
00000020: 002a 0000 0008 0002 0112 0003 0000 0001  .*..............
00000030: 0001 0000 8769 0004 0000 0001 0000 0026  .....i.........&
```

base64 snippet
```
/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAgESAAMAAAAB
AAEAAIdpAAQAAAABAAAAJgAAAAAAAqACAAQAAAABAAADVaADAAQAAAABAAAEcAAA
AAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZ
jwCyBOmACZjs+EJ+/+ICNElDQ19QUk9GSUxFAAEBAAACJGFwcGwEAAAAbW50clJH
```

then wrapping that in body.txt 

 snippet of body.txt with binary:
```
--------------------------c3f12cad39483b9a
Content-Disposition: form-data; name="data"; filename="file1.jpg"
Content-Type: image/jpeg

00000000: ffd8 ffe0 0010 4a46 4946 0001 0100 0048  ......JFIF.....H
00000010: 0048 0000 ffe1 004c 4578 6966 0000 4d4d  .H.....LExif..MM
00000020: 002a 0000 0008 0002 0112 0003 0000 0001  .*..............
00000030: 0001 0000 8769 0004 0000 0001 0000 0026  .....i.........&
{- content of file1.jpg continues -}
--------------------------c3f12cad39483b9a--
```

 snippet of body.txt with base64:
```
--------------------------c3f12cad39483b9a
Content-Disposition: form-data; name="data"; filename="file1.jpg"
Content-Type: image/jpeg

/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAgESAAMAAAAB
AAEAAIdpAAQAAAABAAAAJgAAAAAAAqACAAQAAAABAAADVaADAAQAAAABAAAEcAAA
AAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZ
jwCyBOmACZjs+EJ+/+ICNElDQ19QUk9GSUxFAAEBAAACJGFwcGwEAAAAbW50clJH
{- content of file1.jpg continues -}
--------------------------c3f12cad39483b9a--
```

but yeah still no luck! I should mention that I have used bombardier to test all my other endpoints that don't require jpg/png 😂 and it's _fantastic_ 

Is there anyway I can help with the tool? I'm still getting familiar with golang but maybe we can collaborate on something. 

Thanks for all the help @codesenberg

**Comment by codesenberg** [comment]
Here, maybe you'll have better luck with the files I used:
* [body_with_bin.txt](https://github.com/codesenberg/bombardier/files/1498525/body_with_bin.txt);
* [body_with_base64.txt](https://github.com/codesenberg/bombardier/files/1498526/body_with_base64.txt).

Code of the server I used in my tests:
```go
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"sync"
)

func main() {
	// A lock so we won't get a mishmash of outputs from multiple
	// concurrent requests.
	var outLock sync.Mutex
	http.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
		outLock.Lock()
		defer outLock.Unlock()
		err := r.ParseMultipartForm(40 * 1024 * 1024)
		if err != nil {
			fmt.Println(err)
			rw.WriteHeader(http.StatusBadRequest)
			return
		}
		for _, files := range r.MultipartForm.File {
			for _, file := range files {
				for k, v := range file.Header {
					fmt.Println(k+":", v)
				}
				fmt.Println("Size", file.Size)
				mf, err := file.Open()
				if err != nil {
					fmt.Println("<couldn't open file>")
					continue
				}
				fb, err := ioutil.ReadAll(mf)
				if err != nil {
					fmt.Println("<couldn't read file's content>")
					continue
				}
				fmt.Println("FILE-CONTENT-BEGIN")
				fmt.Println(string(fb))
				fmt.Println("FILE-CONTENT-END")
			}
		}
		fmt.Println()
	})
	http.ListenAndServe("localhost:8080", nil)
}
```

The command:
```bash
bombardier -m POST -n 1 -H "Content-Type: multipart/form-data; boundary=c3f12cad39483b9a" -f "body_with_bin.txt.txt" "localhost:8080/v1/upload_bin?param=int&params=more&again=stuff&finally=thing"
```

All in all, I don't think that there is an issue with _bombardier_, but with the server or files you are using.
Glad to hear that you find my tool _fantastic_ :)
You can probably write a tool to craft multipart requests. Looks like it's fairly easy to make a mistake while making them by hand.

**Comment by codesenberg** [comment]
Oh, and here is the jpeg file I put into those: [jpeg.jpg](https://raw.githubusercontent.com/mathiasbynens/small/ec95d020c81549068f971819dbc62cf8a15e8728/jpeg.jpg) (taken from here — [small](https://github.com/mathiasbynens/small))

**Comment by codesenberg** [comment]
Hey, @her, it's been a week since you wrote here. Have you resolved the issue you've encountered? Is there anything we need to clarify regarding this issue or we can close it?

**Comment by her** [comment]
Hey @codesenberg! Sorry for the radio silence here. US holidays are a time sinking affair 😂

I still haven’t resolved the binary upload load testing however it’s not a time critical task at the moment for me. I was able to get great insight with bombardier on other endpoints and that’s helped greatly. 

If you want to close this feel free! I plan on tinkering around to see if I can get it working a bit later and if I make some progress I’ll definitely let you know, via PRs (best case) or a friendly message. 

Cheers 🍻

**Comment by codesenberg** [comment]
Oh, right, you had a Thanksgiving recently. I'll close this issue then. We can always reopen it, if there is indeed an issue with _bombardier_ after all.

**Comment by SomnathS09** [comment]
Thanks, This helped.
I was having trouble copying binary data of audio file in my case.
Thanks to Notepad++, I was able to do it.
Steps in Notepad++ :
Click File-> Edit -> Paste Special -> Copy Binary Data
Then paste.
