### ISSUE TITLE
Support for the PATCH method?

### ISSUE THREAD

**Issue by bfitzsimmons** [codesenberg/bombardier#22]
Hi there,

Are there any plans for adding support for the `PATCH` HTTP request method?

**Comment by codesenberg** [comment]
@bfitzsimmons, sure. Just pushed [commit](https://github.com/codesenberg/bombardier/commit/c1c176f9eb1f35ce883af726125326bf73741d38) to add PATCH to the list of methods. Should work now, but I haven't tested it extensively, so let me know if something goes wrong.

**Comment by bfitzsimmons** [comment]
It worked for me. Thanks for adding it so quickly!
