### ISSUE TITLE
feature: Prometheus node_exporter compatible output

### ISSUE THREAD

**Issue by greenpau** [codesenberg/bombardier#24]
The output produced by `bombardier` cannot be consumed by Prometheus.

It would be nice to have metrics like this:

![image](https://user-images.githubusercontent.com/3826416/35421558-e5d41754-0211-11e8-96f0-8b1d4acd1564.png)

Prometheus' [node_exporter](https://github.com/prometheus/node_exporter) has [`textfile`](https://github.com/prometheus/node_exporter#textfile-collector) collector. The collector scans directory for `.prom` files and adds the metrics found in the file to its own metrics set.

This way, I can run `bombardier` every minute, output results to `bombardier.prom` file and the metrics will be picked up by Prometheus server.

I would like to come up with a number of metrics and have an option to output results as a Prometheus metric.

For example, the following output:

```
Statistics        Avg      Stdev        Max
  Reqs/sec      6607.00     524.56       7109
  Latency       29.86ms     5.36ms   305.02ms
```

would result in the following metrics:

* `bombardier_http_request_rate_avg`
* `bombardier_http_request_rate_max`
* `bombardier_http_request_rate_stdev`
* `bombardier_http_latency_avg`
* `bombardier_http_latency_stdev`
* `bombardier_http_latency_max`

Each metric could have one or more labels associated with it.

For example, the following command:

```
bombardier -c 200 -d 10s -l http://ya.ru
```

would result in the following metrics:

```
conn: 200
duration: 10
url: http://ya.ru
```

Further, it would be helpful to output UUID associated with each test.

**Comment by greenpau** [comment]
@codesenberg , I was thinking about creating a PR for this. Do you have any view on this one?

**Comment by codesenberg** [comment]
I was thinking about adding two flags `--print (-p)` and `--format (-f)`, so users could do something like:
`bombardier [other flags...] --print=result --format=json <url>`
and get something like:
```
{
	"attack": {
		// attack parameters, i.e url, number of conns., etc.
	},
	"requests_per_second": {
		"avg": 1000,
		"stdev": 200,
		"max": 2000
	},
	"latency": {
		// durations are in microseconds
		"avg": 20000.2,
		"stdev": 5000.0,
		"max": 100000.0,
		// if --latencies flag is used
		"percentiles": {
			"50": 19200.0,
			"75": 21000.0,
			"90": 23000.0,
			"99": 31000.0,
		},
	},
	// throughput is in bytes per second
	"throughput": 10000.0,
	"codes": { /* HTTP status codes */ },
	// some other things I could forget
}
```
With this you could transform said JSON into the format you need. Sounds good?
As for the UUID, you could run some script, like this one:
```bash
(python -c "import sys,uuid; sys.stdout.write("test_uuid: " + uuid.uuid4().hex + '\n')" && bombardier --print=result --format=json <url> | transform-bombardier-output-to-prometheus-format) > bombardier.prom
```

**Comment by codesenberg** [comment]
Just to clarify a little bit `--print=result` means that only the stats will be printed. No intro and no progress bar.

**Comment by codesenberg** [comment]
@greenpau, you know, we could actually step a bit further and just add `prometheus` to the list of formats understood by the `--format` flag, saving users from the hassle of transforming json into prometheus's text format.

**Comment by greenpau** [comment]
>  add prometheus to the list of formats understood by the --format flag,

vot eto razgovor 👍

**Comment by codesenberg** [comment]
Hey, @greenpau, how important that UUID thing for your use case? I plan to implement user-defined templates, so if it's somewhat important (granted I will in fact implement them), I could add some `func UUID() (string|something)` helper.

**Comment by greenpau** [comment]
> UUID thing for your use case?

@codesenberg , it is pretty important, because it allows to store that transaction in other systems, e.g. `elasticsearch`. Consider reading https://discuss.elastic.co/t/elastic-search--id-uuid-format/28801/4 for insights.

**Comment by codesenberg** [comment]
The I'll probably add helpers for all five versions of it from [this library](https://github.com/satori/go.uuid).
Sounds good to you?

**Comment by greenpau** [comment]
> The I'll probably add helpers for all five versions of it from this library.

That's sounds great! 👍

**Comment by codesenberg** [comment]
Ok, user-defined templates landed on master just now. Let me know if everything is in place to generate the output you want.

**Comment by greenpau** [comment]
> Ok, user-defined templates landed on master just now. Let me know if everything is in place to generate the output you want.

@codesenberg , 👍

**Comment by Tkanos** [comment]
Hello @codesenberg,
Let me know if I can help you with the prometheus side.

**Comment by codesenberg** [comment]
@Tkanos, well, I don't know if there is some reasonable default output format for _prometheus_ that we could use. Mainly, because I'm not too familiar with _prometheus_ in general, but if there is one, then sure, we could add it.

**Comment by codesenberg** [comment]
By the way. @greenpau, have you succeeded in your endeavor to generate _prometheus_ compatible output by using user-defined output templates?

**Comment by Tkanos** [comment]
@codesenberg,
Well we can define all the output of bombardier to be scraped by Prometheus, but Prometheus is a time series database, and benchmark is done time to time (or in the CI/CD path), so there is (for me) no real sense.

And the guy that wants to have it, will have to configure Prometheus to scrap the endpoint that we will have to provide. And if he configure it to scrap each 15 sec, and do a benchmark of 5s, He will not have any information, and then after the benchmark he will have to remove his config.

It could have sense in a benchmark Suite, where all benchmark are managed by a web application, that runs all benchmark of all projects, and provide the info to prometheus, but it's not the goal of Bombardier.

Or do what @greenpau is doing, a prom generated, that we can generate during the CI/CD and provide it to prometheus to alert if we have an issue.

**Comment by greenpau** [comment]
> By the way. @greenpau, have you succeeded in your endeavor to generate prometheus compatible output by using user-defined output templates?

@codesenberg , unfortunately, I am tied doing other things at the moment. I think the way you did is with templates is great, because then, using that same templating technique, you could generate Elasticsearch inserts. Once I get back to app testing, I will post in here.

**Comment by codesenberg** [comment]
@Tkanos, let's leave things as they are then. (At least for the time being.)

**Comment by codesenberg** [comment]
I'll close this one, since more than two years passed already. Unlikely that we'll hear any feedback 😄
