### ISSUE TITLE
feature: different output formats

### ISSUE THREAD

**Issue by codesenberg** [codesenberg/bombardier#26]
As a follow-up to #24 and #25, the next feature to resolve #24 is to implement a flag to control output format and some formats (like JSON, XML (?), etc.). The flag will most likely be named `--format` and a shorthand is `-o` (though, this is discussable). I also think it would be great to add support for user-defined templates, since it would be quite bothersome to add templates for all possible formats into the code base.

**Comment by answerquest** [comment]
> I also think it would be great to add support for user-defined templates, since it would be quite bothersome to add templates for all possible formats into the code base.
Any work on that? I'm looking for a CSV output.

**Comment by codesenberg** [comment]
@answerquest the feature is implemented. If you want to add default template for CSV be my guest and send a PR 😉
