### ISSUE TITLE
Compare to other tools 

### ISSUE THREAD

**Issue by janisz** [codesenberg/bombardier#3]
I would like to see comparison with https://github.com/tsenart/vegeta and https://github.com/giltene/wrk2

**Comment by codesenberg** [comment]
I wrote a short [comparison](https://github.com/codesenberg/bombardier/wiki/Comparison-to-other-tools). Looks good to you?

**Comment by janisz** [comment]
Cool!  I'll give bombardier a try and update this file if needed. Thanks
