### ISSUE TITLE
can i input txt file with different URLs in it ?

### ISSUE THREAD

**Issue by rawmaterials** [codesenberg/bombardier#30]
becuase there is caching enabled on my sites and i want to test different urls.,
as if url gets requested twice it gets cached.

so it would be great if we could provide txt file containing list of urls.

thanks

**Comment by codesenberg** [comment]
There is no way to specify multiple URLs, but you could do something in the spirit of UNIX philosophy, i.e., given `urls.txt` looks something like:

```
http://mysite.com/url1
http://mysite.com/url2?with=param
http://mysite.com/url3
```

you can then run:

```bash
cat sites.txt | xargs -P 8 -i bombardier -q "{}"
```

or, if you need outputs (`script.sh`):

```bash
#!/usr/bin/env bash

while read -r url
do
  (bombardier "$url" > "$url.txt") &
done < "${1:-/dev/stdin}"
```

and then, `cat urls.txt | script.sh`.

But maybe, you could try another approach, like, disabling caching on a test server, if it's a feasible option.

**Comment by rawmaterials** [comment]
Thanks, looking in to it., right now i am windows., so will work with batch scripting.

**Comment by ericsouza** [comment]
Hey @codesenberg ! Do you thin there is any change this feature get added? 

I'm using bombardier to benchmark a system that `pops all` elements from a redis list, so after the first call for a single user id all subsequently request for the same user id will return nothing.

 If there was a way to tell bombardier to use a sequence, for example go from 1...1000 in a path like: `localhost:8080/user/{index}/messages` would be amazing. 

[drill, a benchmark tool written in rust](https://github.com/fcsonline/drill) has something similar to this.

By the way, bombardier its an amazing tool!

**Comment by codesenberg** [comment]
Thanks for providing an example of how this functionality might be implemented, @ericsouza.
This or similar feature has been requested a couple of times. We use #84 for discussions these days.
