### ISSUE TITLE
Body Parameter ignored for --http1 and --http2 flags.

### ISSUE THREAD

**Issue by brvi** [codesenberg/bombardier#32]
I build bombardier from source using `go1.10.1 darwin/amd64`. I also cross compiled to `linux/amd64`.

### What version of bombardier are you using?

[db65d7c4537354aabece20b1fbd0127f51145f11](https://github.com/codesenberg/bombardier/commit/db65d7c4537354aabece20b1fbd0127f51145f11)

### What operating system and processor architecture are you using (if relevant)?
`linux/amd64` & `darwin/amd64`

### What did you do?
I noticed requests failing when using the --http1 flag, so I used `requestbin` to log and inspect requests. Turns out that anything passed in via both the `--body`and `--body-file` flags gets ignored for `--http1` and `--http2` flags. I verified this by removing those flags and the requests passed through properly.
### What you expected to happen?
I expect the body to be passed through in post requests when not utilizing `fast-http`
### What actually happened?
The body parameters weren't passed through.

P.S. Thanks for creating this awesome tool.

**Comment by codesenberg** [comment]
Ok, I've investigated this a bit and found out that `requestbin` doesn't display bodies of requests that are sent with chunked transfer encoding (`Transfer-Encoding: chunked`). So, actually, the bodies are sent, but you can't see them in `requestbin`'s request log.
Another thing I found is that `net/http` uses chunked transfer encoding where it shouldn't. This is fixed now, so you will be able to see bodies in `requestbin`'s request log, unless you turn streaming on (`--stream` flag).

**Comment by brvi** [comment]
Wow! Thank you for your thorough investigation, explanation and resolution!
