### ISSUE TITLE
Can I send a request with "Content-Type: application/x-www-form-urlencoded; charset=UTF-8"?

### ISSUE THREAD

**Issue by devguysin** [codesenberg/bombardier#33]
Hi,

I want to do load test for a POST request that the Content-Type: application/x-www-form-urlencoded; charset=UTF-8.

and the form data is:
action=get_data&number=1234

is it possible to do it with bombadier?

Thanks.

**Comment by codesenberg** [comment]
Yes it is:
```bash
bombardier -m POST -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -b "action=get_data&number=1234" http://le-host.fr/other/parts/of/the/url
```

**Comment by codesenberg** [comment]
@devguysin, does that answer your questions? Is there anything else you wanted to know or we can close this issue?

**Comment by devguysin** [comment]
That answers, Thank you!

**Comment by thuandoan274** [comment]
How to send body like
```
{
	"merchant": "56f8f6bdb7bfb8a979db12b5",
	"feedback": "",
	"point": 4
}
```

**Comment by codesenberg** [comment]
@thuandoan274, one does not simply hijack closed issue to ask a question 🙂
![default](https://user-images.githubusercontent.com/6357982/42104888-cb946ce0-7be7-11e8-847d-2f74c4e086bf.png)

**Comment by codesenberg** [comment]
But, well, I can answer it, since it's your your first time.
You put that body in a file and then use `-b` flag. Like this:
```bash
bombardier -b path/to/your/file.json http://some.url.com
```
But if you have other questions, please, use some specialized resource or create a new issue. Ok? Thnx.
