### ISSUE TITLE
Is there a meaning of using a higher amount of connections that rate limit

### ISSUE THREAD

**Issue by devguysin** [codesenberg/bombardier#34]
Hi,

I want to know if there is a meaning of putting a higher amount of connections than the rate limit?

if I am running with c 500 and r 100 I will get a different result than if I run c 100 and r 100.

What is the meaning of it?

Thanks.

**Comment by codesenberg** [comment]
Well, the `c` parameter actually specifies a maximum number of connections per host, so, it might be that the actual number of connections used can be a lot (or a bit) smaller that what specified with `c`.
Other thing is, I'm not quite sure what you mean by "different results". Want to elaborate on this?
