### ISSUE TITLE
'Host' Header cannot be set

### ISSUE THREAD

**Issue by nielsole** [codesenberg/bombardier#41]
### What version of bombardier are you using?
v1.2

### What operating system and processor architecture are you using (if relevant)?
`linux/amd64`

### What did you do?
I need to send a custom Host header. E.g.

```
bombardier http://localhost:8000  -l -o json -p r -c 1 --header="Host: somethingelse" -d 2s
```

### What you expected to happen?
Request 'Host' header would be replaced with my cusotm header

### What actually happened?
The Hostname from the URI was taken into the Host header field.

This has been discussed upstream:
https://github.com/valyala/fasthttp/issues/318

**Comment by codesenberg** [comment]
Closing, but feel free to reopen.
