### ISSUE TITLE
Bombardier with fasthttp option is sending a double slash

### ISSUE THREAD

**Issue by wvh** [codesenberg/bombardier#43]
Hello,

This is a bug report about the latest version of bombardier with hash: [4b1b54923b01b38d1b2b238a87861388c08d3952](https://github.com/codesenberg/bombardier/commit/4b1b54923b01b38d1b2b238a87861388c08d3952)

... running on Linux/amd64 with Go version go1.11.4 linux/amd64.

Running the following command, with or without `http://` prefix:
```shell
bombardier 127.0.0.1:8080/
```
... sends the following sequence (double-checked with `ngrep`):
```
T 127.0.0.1:38682 -> 127.0.0.1:8080 [AP] #51584
GET //? HTTP/1.1
User-Agent: fasthttp
Host: 127.0.0.1:8080
```
Note the double slash.

This problem only occurs with the `fasthttp` option (which is the default), not with `--http1` option.

A quick look makes me guess the problem happens here:
https://github.com/codesenberg/bombardier/blob/master/clients.go#L56
```go
c.requestURI = "/" + u.Path + "?" + u.RawQuery
```

`URL.Path` would return a slash for a URL that has a trailing slash, so the request ends up with two.

**Comment by codesenberg** [comment]
@wvh, thanks for the report. Check out the [latest commit](https://github.com/codesenberg/bombardier/commit/d3689684190b24db738a79d47a764acd00d59794) in the master branch for the fix and don't forget to close the issue if the bug is fixed now :wink:

**Comment by wvh** [comment]
Confirm fixed. Thanks!
