### ISSUE TITLE
Line wrapping at the end of statistics

### ISSUE THREAD

**Issue by n0madic** [codesenberg/bombardier#45]
### What version of bombardier are you using?
`bombardier version v1.2.2`

### What operating system and processor architecture are you using (if relevant)?
`linux/amd64`

### What did you do?

```
nomadic@Dell-Inspiron-5759:~$ bombardier http://ya.ru
Bombarding http://ya.ru:80 for 10s using 125 connection(s)
[=================================================================================================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec       866.94     456.96    5251.28
  Latency      143.78ms    38.89ms      1.33s
  HTTP codes:
    1xx - 0, 2xx - 0, 3xx - 8778, 4xx - 0, 5xx - 0
    others - 0
  Throughput:   554.19KB/snomadic@Dell-Inspiron-5759:~$ 
```

### What you expected to happen?
Line wrapping at the end of statistics

### What actually happened?
Eats line break at the end

**Comment by codesenberg** [comment]
Well, to be precise, it's not eating a line break, because there is none :smile: 
On the other hand, some shells (like, `cmd` on Windows) add it automatically.
I think users won't suffer greatly if I add another one.
