### ISSUE TITLE
invalid memory address or nil pointer dereference when using fasthttp (windows)

### ISSUE THREAD

**Issue by andyphilpotts** [codesenberg/bombardier#46]
Using the windows version of bombardier:

> bombard --version
bombardier version v1.2.3 windows/386

So it basically runs, but if I dare to provide a URL and no other options I get errors (below), This looks like a fasthttp problem, I presume the default, as it will run with OK with --http1 or --http2

Do I have to install a pre-req to use fasthttp?

> bombard https://www.google.com/
Bombarding https://www.google.com:443/ for 10s using 125 connection(s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x401efc]

goroutine 13 [running]:
runtime/internal/atomic.Xadd64(0x11802774, 0x1, 0x0, 0x6ace95, 0x0)
        C:/Go/src/runtime/internal/atomic/asm_386.s:102 +0xc
github.com/codesenberg/bombardier/vendor/github.com/valyala/fasthttp.(*HostClient).Do(0x118026c0, 0x1196c000, 0x11970000, 0x0, 0xada4e0)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/github.com/codesenberg/bombardier/vendor/github.com/valyala/fasthttp/client.go:996 +0x4f
main.(*fasthttpClient).do(0x11820690, 0x11812880, 0x0, 0x11824600, 0x440000, 0x6fdb2b)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/github.com/codesenberg/bombardier/clients.go:101 +0x17d
main.(*bombardier).performSingleRequest(0x11898a20)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/github.com/codesenberg/bombardier/bombardier.go:251 +0x31
main.(*bombardier).worker(0x11898a20)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/github.com/codesenberg/bombardier/bombardier.go:264 +0x47
main.(*bombardier).bombard.func1(0x11898a20)
        C:/Users/frei/Documents/Go/Workspaces/Default/src/github.com/codesenberg/bombardier/bombardier.go:337 +0x4b
created by main.(*bombardier).bombard
        C:/Users/frei/Documents/Go/Workspaces/Default/src/github.com/codesenberg/bombardier/bombardier.go:335 +0xaa

**Comment by codesenberg** [comment]
Hi, @andyphilpotts. No, no pre-reqs are required. This was a bug in `fasthttp` which got fixed in a newer version. Should be fixed on `master` now.
