### ISSUE TITLE
Unable to to go get

### ISSUE THREAD

**Issue by akshaybabloo** [codesenberg/bombardier#49]
When I try to do `go get -u github.com/codesenberg/bombardier` I get the following error

```
build github.com/codesenberg/bombardier: cannot load gopkg.in/mattn/go-colorable.v0: cannot find module providing package gopkg.in/mattn/go-colorable.v0
```

**Comment by kataras** [comment]
@akshaybabloo see https://github.com/codesenberg/bombardier/issues/44#issuecomment-549077572
