### ISSUE TITLE
cannot benchmark url like this

### ISSUE THREAD

**Issue by pugwoo** [codesenberg/bombardier#52]
This is an example of what a **bug report** can look like. Please, feel free to also provide any other information relevant to the issue.

### What version of bombardier are you using?

1.2.4

### What operating system and processor architecture are you using (if relevant)?
all

### What did you do?

run this command:

```bash
bombardier -n 10000 -c 1000 "http://127.0.0.1:8080/to?url=http://10.100.99.41:38667"
```

### What you expected to happen?

start benchmark

### What actually happened?

it outputs:

```
"http://127.0.0.1:8080/to?url=http://" is not an acceptable protocol (http, https): http://127.0.0.1:8080/to?url=http://10.100.99.41:38667
```

**Comment by codesenberg** [comment]
Thanks for the report. This is now fixed in `master`, I'll build and publish a new version some time later.
