### ISSUE TITLE
passing different request Headers per each request from an external file

### ISSUE THREAD

**Issue by gunayus** [codesenberg/bombardier#54]
Is it possible to pass different (random) request Headers per each http request from an external file? if not, would you like to add this feature?

my use case is following, I would like to load test my application but for different user accounts in order to eliminate non-realistic cache hits. my app expects 'Authorization' request header to identify the end user.

**Comment by codesenberg** [comment]
Somewhat similar to #55 I think, but [the answer](https://github.com/codesenberg/bombardier/issues/55#issuecomment-593014496) is the same for this FR.
