### ISSUE TITLE
Supports placeholder in request header and body

### ISSUE THREAD

**Issue by quaff** [codesenberg/bombardier#55]
To simulate different user and payload base on external file.

**Comment by codesenberg** [comment]
This is a nice feature indeed and somewhat similar to #5.
Unfortunately, as of now, I don't have the time required to implement it.

**Comment by quaff** [comment]
External file could be static csv file, or script file to dynamic generate values.

**Comment by codesenberg** [comment]
You mean like a script written in Bash, Lua or some other language?

**Comment by quaff** [comment]
No bash, Lua or JS.

**Comment by quaff** [comment]
A much simple way is reading bodies from file which delimited by blank line or some other rule, then send in round-robin mode, reuse the `-f` and `-n` arguments.

**Comment by codesenberg** [comment]
Ok, got you. I'll consider this feature for v2. No hard promises or ETAs though.

**Comment by quaff** [comment]
You should consider headers per body.

**Comment by codesenberg** [comment]
Unfortunately, I don't have time to implement features these days, but maybe I'll get back to this in some quite distant futures. Closed till then.

**Comment by fuxinhao-crypto** [comment]
sorry, is there any progress?

**Comment by gabrielgrijincu** [comment]
This would be really helpful. Any news on the progress/ availability?

**Comment by codesenberg** [comment]
Hi all. Not sure why you keep posting to a closed issue.
There's #84 now, which is open. The feature is not planned and there's no point in asking for progress updates as nobody (to the best of my knowledge) is working on it.
