### ISSUE TITLE
macOS kernel panic on bombardier benchmark

### ISSUE THREAD

**Issue by ethanent** [codesenberg/bombardier#58]
Not entirely sure that this is the fault of bombardier. Could easily be more relevant to `fasthttp` or even `net`.

This same error did not occur when a similar server was built using `net/http`. The `net` server provided results as expected in the browser.

### What version of bombardier are you using?

[5e387c23434f632213c1039d5f0ada93d6153f1e](https://github.com/codesenberg/bombardier/commit/5e387c23434f632213c1039d5f0ada93d6153f1e)

### What operating system and processor architecture are you using (if relevant)?

`darwin/amd64`

macOS 10.15.5 (Catalina)

Go version: `go version go1.13.7 darwin/amd64`

### What did you do?

Run package containing:
```
package main

import (
	"fmt"
	"net"
)

func main() {
	l, err := net.Listen("tcp", ":8081")

	if err != nil {
		panic(err)
	}

	for {
		conn, err := l.Accept()

		if err != nil {
			fmt.Println(err)

			continue
		}

		go handleConn(conn)
	}
}

func handleConn(c net.Conn) {
	defer c.Close()
	c.Write([]byte(`HTTP/1.1 200 OK
Content-Length: 50

Information about your request:
URL: /
Method: GET
`))
}
```

Then run command;
`bombardier -l localhost:8081`

### What you expected to happen?

Some results to be printed to console.

### What actually happened?

System kernel panic. Upon system restart, received error beginning with:
```
panic(cpu 0 caller 0xffffff801cac2c5f): assertion failed: NETNS_REF_COUNT(res, flags) != 0, file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.121.2/bsd/skywalk/namespace/netns.c, line: 830
```

**Comment by codesenberg** [comment]
That's weird. Might be some issue with networking implementation. Feel free to re-open if you have more details and really want this stuff to be investigated.
