### ISSUE TITLE
Is it possible to replace a field in the request body from file content/s

### ISSUE THREAD

**Issue by bluedog13** [codesenberg/bombardier#62]
Is there a way to have the benchmarking tool Bombardier read portion of input from a file and substitute this in the request body?
I want to test for x number of ID's with rest of the request body being the same. 

As an example
bombardier -c 125 -n 10000000 -b {"id": < fromfile >, "somefield": "yes"} http://localhost:8080

How can the above value < from file > be replaced by the actual file contents?

**Comment by codesenberg** [comment]
Not at the moment. Unfortunately, I don't have time to implement features these days too.

**Comment by codesenberg** [comment]
But I think [this PR](https://github.com/codesenberg/bombardier/pull/57) adds functionality to do random IDs. Not quite what you're asking for, but maybe, you could patch it to add the desired functionality. Hope this helps a bit.
