### ISSUE TITLE
Question on benchmarking static files serving responses

### ISSUE THREAD

**Issue by mananamenos** [codesenberg/bombardier#65]
Hi, this command `bombardier -c 1700 -d 10s -n 1700 -l https://myapp.com/big-js-file.js` tests a nodejs static files serving endpoint to serve this 1MB size js file. The results report 40s average latency, 99% - 1min 23s. Moreover, only 45 requests have completed with 2xx status while the rest fail with i/o timeout error. Are the results of this simulation representative compared to a real situation, where these 1700 request would be made from diferent computers? My thinking here is that as all the requests thrown by bombardier use the same network interface/card, all theses responses needed to be put in queue and that's why I see such a huge latency. Or am I misunderstanding something?
Thank you

**Comment by sebastienros** [comment]
I would assume that with this load you are maxing out the network, and because you have so many in-flights requests, most of them can't finish before it times-out.
