### ISSUE TITLE
How to use it for https?

### ISSUE THREAD

**Issue by ducpx** [codesenberg/bombardier#68]
I can't use the tool for testing https. The result shows 5xx.

**Comment by shirejoni** [comment]
if you want to send HTTPS request in local, you should give path of .cert and .key files that you generated for backend as `--cert` and `--key` flag.

![image](https://user-images.githubusercontent.com/44242465/104319515-3999c980-54f6-11eb-80ea-c4eccef6a46b.png)

boombardier use golang net/http package for Request(http or [https](https://github.com/codesenberg/bombardier/blob/ba2c55f7f39b198f98a7ce5833e84ae8608ffcea/client_cert.go#L12)) and you can get more info by seeing detail of net/http package for https request or google it 😄

**Comment by codesenberg** [comment]
Actually, there's no need to generate certificates @ducpx, just supply URL with https scheme, like so:

```shell
bombardier https://google.com
```
