### ISSUE TITLE
Add comparison with fasthttploader

### ISSUE THREAD

**Issue by hagen1778** [codesenberg/bombardier#7]
Hi! I am finding that https://github.com/hagen1778/fasthttploader is very similar to yours and it also uses fasthttp. Could you add comparison with that tool?

**Comment by codesenberg** [comment]
Actually, _fasthttp_ aside, these two tools don't look similar to me.
The most similar tool I found(waaay after I wrote _bombardier_) was [gobench](https://github.com/cmpxchg16/gobench).
I liked pretty graphs that your tool generated, but was a bit disappointed to see [QPS drop](http://imgur.com/a/cE7K4)(~2.2 slower than _bombardier_, according to console output).
With all that said, I'm not very interested in such comparison.
Thank you for your interest in my tool.
