### ISSUE TITLE
Apple Silicon build?

### ISSUE THREAD

**Issue by sschlesier** [codesenberg/bombardier#70]
I was about to PR in a change to add an Apple Silicon build, and I see that darwin arm64 was dropped from the build.py in October.

Is there a known problem with that build?  I've built it locally and it appears to work fine.

**Comment by codesenberg** [comment]
Hi, @sschlesier, no idea why I removed it in [this commit](https://github.com/codesenberg/bombardier/commit/ba2c55f7f39b198f98a7ce5833e84ae8608ffcea). [Added it back](https://github.com/codesenberg/bombardier/commit/7871b16dc77ec3121d7ceb9ef47d42416a8bf9f1).

**Comment by stevo-knievo** [comment]
I guess there is no release since? I'm looking for an `bombardier-darwin-arm64` release.
https://github.com/codesenberg/bombardier/releases/tag/v1.2.5

Thank  you
