### ISSUE TITLE
TLS insecure mode and Client Certificate Support

### ISSUE THREAD

**Issue by husobee** [codesenberg/bombardier#8]
I have a use case where I would like to benchmark a service that is protected with TLS Client Certificates, as well as allowing insecure TLS mode for development servers.  I don't feel like this would be too difficult, as all we need to do is add TLSCertificates to a TLS config that should be set on the fasthttp Client.

I have coded up a solution: https://github.com/codesenberg/bombardier/compare/master...husobee:master and am more than happy to PR this if you are willing to consider it.  Thanks!

**Comment by codesenberg** [comment]
Your reasoning seems sound, but your code needs some work before I will be able to merge it, so feel free to send me a PR, so we can start working on it.
