### ISSUE TITLE
Can the stress test of random parameters be realized?

### ISSUE THREAD

**Issue by zhenlei520** [codesenberg/bombardier#81]
### What version of bombardier are you using?

```
bombardier --version v1.2.5
```

### What operating system and processor architecture are you using (if relevant)?

linux/amd64

### What did you do?

I hope that the function of random parameters can be realized, but unfortunately no relevant information can be found

**Comment by codesenberg** [comment]
This seems to ask roughly the same as #84. I'll close this issue to deduplicate.
