### ISSUE TITLE
new release tag?

### ISSUE THREAD

**Issue by ozbillwang** [codesenberg/bombardier#89]
the latest tag was created in Oct 2020. Are we going to manage the release with release tags or only pick up from latest commit in master branch?

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/8954908/163069378-390392d8-0855-4037-861d-b1533ebd4ab0.png">

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/8954908/163069497-5951ff2b-31a2-4dab-8816-7c210503b05f.png">

**Comment by codesenberg** [comment]
Yeah, my bad. There haven't been many changes to `bombardier` since the last release, but I plan to do one soon-ish.

**Comment by codesenberg** [comment]
[Release v1.2.6](https://github.com/codesenberg/bombardier/releases/tag/v1.2.6) was published just now.
