### ISSUE TITLE
bombardier version unspecified

### ISSUE THREAD

**Issue by Kapsonfire-DE** [codesenberg/bombardier#92]
Im installing bombardier in a Docker and `bombardier --version` outputs `bombardier version unspecified linux/amd64`

```dockerfile
#### install go && bombardier
RUN wget https://go.dev/dl/go1.19.1.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.1.linux-amd64.tar.gz
RUN echo 'export PATH=$PATH:/usr/local/go/bin:~/go/bin' >> ~/.bashrc
RUN source ~/.bashrc
RUN go install github.com/codesenberg/bombardier@latest
RUN bombardier --version
```

**Comment by SomnathS09** [comment]
same error for me on windows OS : 
bombardier version unspecified windows/amd64

**Comment by codesenberg** [comment]
This is working as expected. Only [releases](https://github.com/codesenberg/bombardier/releases) get a version tag, if you build bombardier from source it's not clean what the version should be. It could be possible to use HEAD's revision hash, but adding dependency on Git seems impractical.

**Comment by meixger** [comment]
On Windows actual latest version 2.0.2 shows `bombardier version unspecified windows/amd64`
The actual previous version 2.0.1 shows `bombardier version v2.0.1 windows/amd64`
