### ISSUE TITLE
incorrect computation of stddev?

### ISSUE THREAD

**Issue by RobertHenry6bev** [codesenberg/bombardier#95]
https://github.com/codesenberg/bombardier/blob/6b8035ac74d3b4fd39a6db980a20ba5ac2ce49dc/internal/test_info.go#L177

Per https://www.geeksforgeeks.org/python-statistics-stdev/ shouldn't the numerator read (float(count64)-1) ?

**Comment by codesenberg** [comment]
I guess using [Bessel's correction](https://en.wikipedia.org/wiki/Bessel%27s_correction) here wouldn't hurt. Though, for larger _request counts_ (if _request count_ > 75 the bias is below 1%) using [uncorrected sample deviation](https://en.wikipedia.org/wiki/Standard_deviation#Uncorrected_sample_standard_deviation) should be acceptable.
